//! SeaORM Entity. Generated by sea-orm-codegen 0.10.1

use crate::api::args::SpawnpointTth;

use super::*;

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "spawnpoint")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: u64,
    pub lat: f64,
    pub lon: f64,
    pub updated: u32,
    pub last_seen: u32,
    pub despawn_sec: Option<u16>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

pub struct Query;

impl Query {
    pub async fn all(
        conn: &DatabaseConnection,
        last_seen: u32,
        tth: SpawnpointTth,
        point_limit: u64,
    ) -> Result<Vec<GenericData>, DbErr> {
        let items = spawnpoint::Entity::find()
            .select_only()
            .column(spawnpoint::Column::Lat)
            .column(spawnpoint::Column::Lon)
            .column(spawnpoint::Column::DespawnSec)
            .limit((point_limit != 0).then_some(point_limit))
            .filter(spawnpoint::Column::LastSeen.gt(last_seen))
            .filter(match tth {
                SpawnpointTth::All => Column::Id.is_not_null(),
                SpawnpointTth::Known => Column::DespawnSec.is_not_null(),
                SpawnpointTth::Unknown => Column::DespawnSec.is_null(),
            })
            .into_model::<Spawnpoint>()
            .all(conn)
            .await?;
        Ok(utils::normalize::spawnpoint(items))
    }

    pub async fn bound(
        conn: &DatabaseConnection,
        payload: &api::args::BoundsArg,
    ) -> Result<Vec<GenericData>, DbErr> {
        let point_limit = api::args::resolve_point_limit(payload.point_limit);
        let items = spawnpoint::Entity::find()
            .select_only()
            .column(spawnpoint::Column::Lat)
            .column(spawnpoint::Column::Lon)
            .column(spawnpoint::Column::DespawnSec)
            .filter(spawnpoint::Column::Lat.between(payload.min_lat, payload.max_lat))
            .filter(spawnpoint::Column::Lon.between(payload.min_lon, payload.max_lon))
            .filter(Column::LastSeen.gt(payload.last_seen.unwrap_or(0)))
            .filter(match payload.tth.as_ref().unwrap_or(&SpawnpointTth::All) {
                SpawnpointTth::All => Column::Id.is_not_null(),
                SpawnpointTth::Known => Column::DespawnSec.is_not_null(),
                SpawnpointTth::Unknown => Column::DespawnSec.is_null(),
            })
            .limit((point_limit != 0).then_some(point_limit))
            .into_model::<Spawnpoint>()
            .all(conn)
            .await?;
        Ok(utils::normalize::spawnpoint(items))
    }

    async fn query_area(
        conn: &DatabaseConnection,
        area: &FeatureCollection,
        last_seen: u32,
        tth: SpawnpointTth,
        point_limit: u64,
    ) -> Result<Vec<Spawnpoint>, DbErr> {
        let rows = spawnpoint::Entity::find()
            .from_raw_sql(Statement::from_sql_and_values(
                DbBackend::MySql,
                format!(
                    "SELECT lat, lon, despawn_sec FROM spawnpoint WHERE last_seen > {} {} AND ({})",
                    last_seen,
                    match tth {
                        SpawnpointTth::All => "".to_string(),
                        SpawnpointTth::Known => "AND despawn_sec IS NOT NULL".to_string(),
                        SpawnpointTth::Unknown => "AND despawn_sec IS NULL".to_string(),
                    },
                    utils::sql_raw_bbox(area)
                )
                .as_str(),
                vec![],
            ))
            .into_model::<Spawnpoint>()
            .stream(conn)
            .await?;
        utils::normalize::collect_in_area(rows, area, point_limit).await
    }

    pub async fn area(
        conn: &DatabaseConnection,
        area: &FeatureCollection,
        last_seen: u32,
        tth: SpawnpointTth,
        point_limit: u64,
    ) -> Result<Vec<GenericData>, DbErr> {
        let items = Self::query_area(conn, area, last_seen, tth, point_limit).await?;
        Ok(utils::normalize::spawnpoint(items))
    }

    pub async fn stats(
        conn: &DatabaseConnection,
        area: &FeatureCollection,
        last_seen: u32,
        tth: SpawnpointTth,
    ) -> Result<Total, DbErr> {
        let items = Self::query_area(conn, area, last_seen, tth, 0).await?;
        let total = items.len() as i32;
        Ok(Total { total })
    }
}
